version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./app:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
